os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
script:
  - curl -sL swift.qutheory.io/07-20 | bash
  # Build Core
  - swift build
  - swift build --configuration release
  # Test Core
  - swift test
