os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
before_install:
  - curl -sL swift.qutheory.io/07-20 | bash
script:
  - export PATH=$HOME/swift/usr/bin:"{$PATH}"
  # Build Core
  - swift build
  - swift build --configuration release
  # Test Core
  - swift test
