os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL swift.qutheory.io/travis)"
script:
  # Build Core
  - swift build
  - swift build --configuration release
  # Test Core
  - swift test
after_success:
  - bash <(curl -s https://codecov.io/bash)
