version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


  linux-vapor:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone Vapor
          command: git clone -b master https://github.com/vapor/vapor.git
          working_directory: ~/
      - run:
          name: Switch Vapor to this Core revision
          command: swift package edit Core --revision $CIRCLE_SHA1
          working_directory: ~/vapor
      - run:
          name: Run Vapor unit tests
          command: swift test
          working_directory: ~/vapor


  linux-fluent:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone Fluent SQLite
          command: git clone -b master https://github.com/vapor/fluent-sqlite.git
          working_directory: ~/
      - run:
          name: Switch Fluent SQLite to this Core revision
          command: swift package edit Core --revision $CIRCLE_SHA1
          working_directory: ~/fluent-sqlite
      - run:
          name: Run Fluent unit tests
          command: swift test
          working_directory: ~/fluent-sqlite


workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-vapor
      - linux-fluent
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      # - macos
      